# Generated by Django 3.1.1 on 2021-05-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='user',
        ),
    ]
